language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - pypy3
env:
  global:
    - SYMPY_SRC=sympy-1.4
    - DOC="false"
    - ALL_MODULES="false"
    - CYTHON="false"
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: DOC="true"
    - python: 3.6
      env: ALL_MODULES="true"
    - python: 3.6
      env: CYTHON="true"
    - python: 3.6
      env: ALL_MODULES="true" CYTHON="true"
  allow_failures:
    - python: pypy3
    - env: SYMPY_SRC=master
    - env: DOC="true"
services:
  - xvfb
before_install:
  - pip install numpy
  - if [[ "$ALL_MODULES" == "true" ]]; then
      sudo apt-get update -qq &&
      sudo apt-get install -qq python-enchant &&
      pip install ipywidgets ipykernel requests IPython==5.0.0 nltk langid pycountry pyenchant lxml matplotlib networkx &&
      python travis.py &&
      python -m nltk.downloader wordnet omw;
    fi
  - if [[ "$DOC" == "true" ]]; then
      sudo apt-get update -qq &&
      sudo apt-get install -qq asymptote imagemagick texlive-latex-extra texlive-latex3 texlive-fonts-recommended latexmk;
    fi
  - if [[ "$CYTHON" == "true" ]]; then
      pip install cython;
    fi
  - pip install pint unittest2 pexpect
  - pip install git+https://github.com/sympy/sympy.git@$SYMPY_SRC
install:
  - sed -i "s/'sympy==[0-9]\.[0-9]\.[0-9]', //" setup.py
  - if [[ "$DOC" == "true" ]]; then python setup.py develop; else python setup.py install; fi
script:
  - python setup.py test
  - if [[ "$DOC" == "true" ]]; then
      python mathics/test.py -o &&
      python mathics/test.py -t &&
      cd mathics/doc/ &&
      ./images.sh &&
      cd tex/ &&
      make latex;
    else
      python mathics/test.py;
    fi
notifications:
    email: false
    slack: mathics:VIjdkcZPlA79sOtVOtyjdOcT
